using Microsoft.AspNet.Identity.EntityFramework;
using Hurtownia.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin;
using Microsoft.Owin.Security;
using System.Threading.Tasks;
using Hurtownia.DAL;
using Hurtownia.Migrations;
using System.Data.Entity.Migrations;

namespace Hurtownia.DAL
{
    public class StoreInitializer : MigrateDatabaseToLatestVersion<StoreContext, Configuration>
    //public class StoreInitializer : DropCreateDatabaseAlways<StoreContext>
    {
        //protected override void Seed(StoreContext context)
        //{
        //    SeedStoreData(context);
        //    base.Seed(context);
        //}

        public static void SeedStoreData(StoreContext context)
        {
            var categories = new List<Category>
            {
                new Category(){CategoryId=1,NameCategory="Nadciśnienie",Description="Leki na nadciśnienie",IconFilename = "szczepionki.png"},
                new Category(){CategoryId=2,NameCategory="Kosmetyki",Description="Kategoria lekow na recepte",IconFilename = "kosmetyki.png"},
                new Category(){CategoryId=3,NameCategory="Mięśnie i stawy",Description="Kontuzje sportowa, wiek, czy specyficzne schorzenia - niezależnie od przyczyn bólom i skurczom mięśniowym możemy skutecznie przeciwdziałać.",IconFilename = "Witaminy.png"},
                new Category(){CategoryId=4,NameCategory="Suplementy",Description="Suplementy  pomagające w uzupełnieniu diety, dodatek zawierający niezbędne dla zdrowia składniki ",IconFilename = "Witaminy.png"},
                new Category(){CategoryId=5,NameCategory="Inne",Description="Pozostałe leki, które nie zostały przyporządkowane do żadnej z wcześniejszych kategorii",IconFilename = "Witaminy.png"},

            };

            categories.ForEach(c => context.Categories.AddOrUpdate(c));
            context.SaveChanges();

            var comments = new List<Comment>
            {
                new Comment(){CommentId=1,Description="sadkjjdsalkjdsaljdsalk",UserName="Admin"},
                new Comment(){CommentId=2,Description="sadkjjdsalkjdsaljdsalk",UserName="Admin"},
                new Comment(){CommentId=3,Description="sadkjjdsalkjdsaljdsalk",UserName="Admin"},

            };

            comments.ForEach(c => context.Comments.AddOrUpdate(c));
            context.SaveChanges();

            var manufactures = new List<Manufacture>
            {
                new Manufacture(){ManufactureId=1,Name="Almirall Hermal GmbH",Address="Ul.Pileckiego 63",CodeAndCity="02-781 Warszawa",Nip="823-111-23-22",PhoneNumber="373848393"},
                new Manufacture(){ManufactureId=2,Name="Silesiun Pharma Sp. z o.o.",Address="ul. Rzepakowa 45",CodeAndCity="40-581 Katowice",Nip="743-146-90-34",PhoneNumber="395394394"},
                new Manufacture(){ManufactureId=3,Name="CN Polfa S.A.",Address="Ul. Przemysłowa 2",CodeAndCity="02-883 Warszawa",Nip="894-235-43-54",PhoneNumber="281032032"},
                new Manufacture(){ManufactureId=4,Name="Zakład Chemiczno-Farmaceutyczny „FARMAPOL” Sp. z o.o.",Address="ul. Św. Wojciech 29",CodeAndCity="61-749 Poznań",Nip="123-235-43-54",PhoneNumber="876532032"},
                new Manufacture(){ManufactureId=5,Name="KENAY AG.",Address="ul. Częstochowska 25",CodeAndCity="62-800 Kalisz",Nip="432-235-22-54",PhoneNumber="355322032"},

            };

            manufactures.ForEach(c => context.Manufactures.AddOrUpdate(c));
            context.SaveChanges();

            var products = new List<Product>
            {
                new Product() { ProductId = 1, ProductName = "Reliver x 10 kaps", ProductDescription = "Suplement diety zalecany dla osób, których wątroba narażona jest na działanie  alkoholu, leków i dieta ciężkostrawna.Wspomaga prawidłowe funkcjonowanie wątroby.", ProductPrice = 16.59m, CoverFileName = "1.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 02, 23),Prescription = true,MaxQuantity = 100,ManufactureId=1, Components="lecytyna rzepakowa, składnik otoczki: żelatyna wołowa, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych, wodny ekstrakt z liści karczocha (Cynara scolymus L.) DER 6:1, standaryzowany na 5% cynaryny, substancja wypełniająca: celuloza, L-asparaginian L-ornityny, substancja przeciwzbrylająca: dwutlenek krzemu, barwnik: dwutlenek tytanu, chlorowodorek pirydoksyny (witamina B6), ryboflawina (witamina B2)",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu.",Form="Zalecana porcja do spożycia w ciągu dnia: 1 kapsułka 1-2 razy dziennie w trakcie lub po posiłku."},
                new Product() { ProductId = 2, ProductName = "FullRutin x 90 tabl", ProductDescription = "Rodzina Zdrowia FullRutin to suplement diety, który dzięki zawartym w nim składnikom pomaga w prawidłowym funkcjonowaniu układu odpornościowego oraz naczyń krwionośnych.\nRutyna jest naturalnym związkiem pochodzenia roślinnego, należącym do grupy flawonoidów, otrzymywanym z perełkowca japońskiego.\nWitamina C pomaga w prawidłowym funkcjonowaniu układu odpornościowego, pomaga w ochronie komórek przed stresem oksydacyjnym oraz przyczynia się do zmniejszenia uczucia zmęczenia i znużenia. Pomaga w prawidłowej produkcji kolagenu w celu zapewnienia prawidłowego funkcjonowania naczyń krwionośnych.\nCynk pomaga w prawidłowym funkcjonowaniu układu odpornościowego i w utrzymaniu prawidłowych funkcji poznawczych.\nSelen pomaga w prawidłowym funkcjonowaniu układu odpornościowego.", ProductPrice = 16.59m, CoverFileName = "fullrutin.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 03, 11),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="substancja wypełniająca: celuloza, kwas L-askorbinowy (witamina C), rutyna, glukonian cynku (cynk),wodno-alkoholowy ekstrakt z pomarańczy gorzkiej (Citrus Aurantium) DER 6:1, standaryzowany na zawartość bioflawonoidów cytrusowych 40%, substancja glazurująca: hydroksypropylometyloceluloza, substancje przeciwzbrylające: sole magnezowe kwasów tłuszczowych, dwutlenek krzemu, selenian (IV) sodu (selen), barwnik: dwutlenek tytanu, substancje glazurujące: glikol polietylenowy, guma arabska, poliwinylopirolidon, barwnik: ryboflawina",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 1-2 tabletki dziennie."},
                new Product() { ProductId = 3, ProductName = "LactiBiotic x 10 kaps", ProductDescription = " Suplement diety Rodzina Zdrowia LactiBiotic przeznaczony jest dla dzieci od 3. roku życia, młodzieży i dorosłych. Zawarte w suplemencie diety bakterie są składnikiem naturalnej flory bakteryjnej człowieka. Produkt zawiera również prebiotyk - inulinę.\nDla dzieci, młodzieży i dorosłych jako uzupełnienie całodziennej diety w trakcie antybiotykoterapii. Zawiera mieszankę 10 wyselekcjonowanych, liofilizowanych, żywych szczepów bakterii kwasu mlekowego oraz prebiotyk – inulinę.", ProductPrice = 7.85m, CoverFileName = "latibioc.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 03, 11),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="glukoza, inulina, składnik otoczki: żelatyna wołowa, mieszanka bakterii Lactobacillus acidophilus, Lactobacillus casei, Lactobacillus rhamnosus, Bifidobacterium breve, Lactobacillus plantarum, Bifidobacterium longum, Bifidobacterium bifidum, Lactobacillus helveticus, Lactococcus lactis ssp lactis, Streptococcus thermophilus, stabilizator: askorbinian sodu, substancje przeciwzbrylające: sole magnezowe kwasów tłuszczowych, dwutlenek krzemu, barwnik: dwutlenek tytanu",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 1 kapsułka dziennie, popijając szklanką zimnego lub letniego płynu (np. woda, mleko). Kapsułkę można też otworzyć a następnie rozpuścić jej zawartość w zimnym lub letnim płynie (np. woda, mleko). Preparat należy spożyć po przygotowaniu."},
                new Product() { ProductId = 4, ProductName = "MagnesiveB6 x 50 tabl", ProductDescription = "Dla młodzieży i osób dorosłych.\nMagnez i witamina B6 przyczyniają się do zmniejszenia uczucia zmęczenia i znużenia, pomagają w prawidłowym funkcjonowaniu układu nerwowego oraz w utrzymaniu prawidłowych funkcji psychologicznych.\nMagnez pomaga w prawidłowym funkcjonowaniu mięśni.\nWitamina B6 pomaga w prawidłowym funkcjonowaniu układu odpornościowego oraz w prawidłowej produkcji czerwonych krwinek.\nZawarty w produkcie magnez występuje w postaci soli organicznej, która należy do dobrze przyswajalnych związków.", ProductPrice = 10.98m, CoverFileName = "magnesive.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 06, 15),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="magnez (mleczan magnezu, substancja wiążąca: poliwinylopirolidon), substancja wypełniająca: celuloza (celuloza mikrokrystaliczna), substancja wiążąca: poliwinylopirolidon, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych (stearynian magnezu), substancja przeciwzbrylająca: dwutlenek krzemu, witamina B6 (chlorowodorek pirydoksyny), stabilizator: poliwinylopolipirolidon",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 2 tabletki dziennie, najlepiej podczas lub po posiłku. Tabletkę należy popić wodą."},
                new Product() { ProductId = 5, ProductName = "Melissive x 20 kaps", ProductDescription = "Melissive to suplement diety polecany dla osób prowadzących stresujący tryb życia. Dzięki zawartym w nim składnikom wspomaga relaks w dzień, a wieczorem pomaga spokojnie zasnąć.\nEkstrakty z ziela melisy i koszyczka rumianku wspomagają relaks oraz psychiczne i fizyczne dobre samopoczucie. Pomagają w utrzymaniu zdrowego snu. Dodatkowo ekstrakt z ziela melisy pomaga w zasypianiu oraz pomaga zmniejszyć napięcie i rozdrażnienie.\n Magnez i witamina B6 pomagają w prawidłowym funkcjonowaniu układu nerwowego oraz w utrzymaniu prawidłowych funkcji psychologicznych. Przyczyniają się do zmniejszenia uczucia zmęczenia i znużenia.\nEkstrakt z korzenia różeńca górskiego pomaga stymulować układ nerwowy oraz wpływa na zdolności umysłowe i poznawcze.", ProductPrice = 13.58m, CoverFileName = "melisive.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 09, 18),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="ekstrakt wodny z ziela melisy (Melissa officinalis) DER 7:1 standaryzowany na zawartość polifenoli 8%, tlenek magnezu (magnez), składnik otoczki: żelatyna wołowa, ekstrakt wodno-alkoholowy z korzenia rózeńca górskiego (Rhodiola rosea) DER 5:1 standaryzowany na zawartość polifenoli 45% i salidrozyd 1%, ekstrakt wodno-alkoholowy z koszyczka rumianku (Matricaria recutita) DER 4:1, substancje przeciwzbrylające: sole magnezowe kwasów tłuszczowych, dwutlenek krzemu, barwnik: tlenki i wodorotlenki żelaza, substancja wypełniająca: celuloza, chlorowodorek pirydoksyny (witamina B6), barwnik: dwutlenek tytanu",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 1 kapsułka dziennie."},
                new Product() { ProductId = 6, ProductName = "Żuramix x 10 tabl", ProductDescription = "Żuramix to suplement diety składający się z ekstraktu z liści pokrzywy, ekstraktu z owoców żurawiny wielkoowocowej zawierającej 50% proantocyjanidyn oraz witaminy C.\nDzięki ekstraktowi z liści pokrzywy wspomaga prawidłowe funkcjonowanie układu moczowego.\nEkstrakt z liści pokrzywy wspomaga funkcje wydalnicze nerek.\nWitamina C pomaga w prawidłowym funkcjonowaniu układu odpornościowego i w ochronie komórek przed stresem oksydacyjnym.\nSuplement diety nie jest przeznaczony dla dzieci poniżej 12 roku życia.", ProductPrice = 16.54m, CoverFileName = "zuramix.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 09, 15),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="magnez (mleczan magnezu, substancja wiążąca: poliwinylopirolidon), substancja wypełniająca: celuloza (celuloza mikrokrystaliczna), substancja wiążąca: poliwinylopirolidon, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych (stearynian magnezu), substancja przeciwzbrylająca: dwutlenek krzemu, witamina B6 (chlorowodorek pirydoksyny), stabilizator: poliwinylopolipirolidon",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 2 tabletki dziennie, najlepiej podczas lub po posiłku. Tabletkę należy popić wodą."},
                new Product() { ProductId = 7, ProductName = "BodyFit x 60 tabl", ProductDescription = " SlimFit dzięki odpowiednio dobranym składnikom stanowi uzupełnienie diety odchudzającej.\nEkstrakt z liści ostrokrzewu paragwajskiego pomaga w utrzymaniu prawidłowej masy ciała oraz przyczynia się do rozkładu tłuszczów.\nEkstrakt z kłącza ostryżu długiego przyczynia się do lepszego trawienia tłuszczów, pomaga wspierać proces trawienia oraz wspomaga prawidłowe funkcjonowanie wątroby. Zapobiega również gromadzeniu się tłuszczów oraz ułatwia ich usuwanie przez wątrobę.\nEkstrakt z liści zielonej herbaty pomaga kontrolować prawidłową masę ciała, wspiera rozkład tłuszczów. Ponadto wspomaga metabolizm oraz pomaga zmniejszyć apetytu.\nEkstrakt z nasion gorzkiej pomarańczy wspomaga metabolizm tłuszczów i węglowodanów oraz przyczynia się do utrzymania prawidłowej masy ciała.\nChrom pomaga w utrzymaniu prawidłowego poziomu glukozy we krwi oraz prawidłowego metabolizmu makroskładników odżywczych.", ProductPrice = 12.98m, CoverFileName = "bodyfit.png", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 06, 15),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="Substancja wypełniająca: celuloza, ekstrakt z liści ostrokrzewu paragwajskiego (Yerba mate) Ilex Paraguariensis DER 2:1, ekstrakt z kłącza ostryżu długiego Curcuma longa DER 4:1, ekstrakt z liści zielonej herbaty Camellia sinensis DER 4:1, substancja przeciwzbrylająca: fosforan wapnia, (fosforan diwapniowy), ekstrakt z nasion gorzkiej pomarańczy Citrus aurantium DER 20:1 ",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu.\nNie zaleca się stosować w okresie ciąży i karmienia piersią.\nProdukt nie jest przeznaczony dla dzieci.",Form="Zalecana porcja do spożycia w ciągu dnia: 2 tabletki dziennie, najlepiej podczas lub po posiłku. Tabletkę należy popić wodą."},   
                new Product() { ProductId = 8, ProductName = "HydroFit x 10 tabl", ProductDescription = "HydroFit  to suplement diety składający się z ekstraktu z liści pokrzywy, ekstraktu z owoców żurawiny wielkoowocowej zawierającej 50% proantocyjanidyn oraz witaminy C.\nDzięki ekstraktowi z liści pokrzywy wspomaga prawidłowe funkcjonowanie układu moczowego.\nEkstrakt z liści pokrzywy wspomaga funkcje wydalnicze nerek.\nWitamina C pomaga w prawidłowym funkcjonowaniu układu odpornościowego i w ochronie komórek przed stresem oksydacyjnym.\nSuplement diety nie jest przeznaczony dla dzieci poniżej 12 roku życia.", ProductPrice = 21.54m, CoverFileName = "hydro.png", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 03, 10),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="magnez (mleczan magnezu, substancja wiążąca: poliwinylopirolidon), substancja wypełniająca: celuloza (celuloza mikrokrystaliczna), substancja wiążąca: poliwinylopirolidon, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych (stearynian magnezu), substancja przeciwzbrylająca: dwutlenek krzemu, witamina B6 (chlorowodorek pirydoksyny), stabilizator: poliwinylopolipirolidon",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="Zalecana porcja do spożycia w ciągu dnia: 3 tabletki dziennie, najlepiej podczas lub po posiłku. Tabletkę należy popić wodą."},
                new Product() { ProductId = 9, ProductName = "FlexiProtect x 60 kaps", ProductDescription = "FlexiProtect polecany jest osobom chcącym zachować sprawność stawów, aktywnym, uprawiającym sport oraz osobom starszym. Dzięki zawartym w nim składnikom pomaga utrzymać elastyczność i sprawność ruchową stawów oraz zapewnia prawidłowe funkcjonowanie kości.\nDzięki ekstraktowi z liści pokrzywy wspomaga prawidłowe funkcjonowanie układu moczowego.\nEkstrakt z liści pokrzywy wspomaga funkcje wydalnicze nerek.\nWitamina C pomaga w prawidłowym funkcjonowaniu układu odpornościowego i w ochronie komórek przed stresem oksydacyjnym.", ProductPrice = 14.32m, CoverFileName = "flexi.png", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 11, 21),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="Zhydrolizowane składniki tkanki chrzęstnej pochodzenia kurzego (w tym kolagen typu II, siarczan chondroityny, kwas hialuronowy), składnik otoczki: żelatyna wołowa, witamina C (kwas L-askorbinowy), ekstrakt z kłącza imbiru lekarskiego (Zingiber officianale Roscoe) DER 10:1, standaryzowany na zawartość gingeroli 0,5%-1%, ekstrakt z owoców dzikiej róży (Rosa canina L.) DER 4:1, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych, kwas hialuronowy, substancja przeciwzbrylająca: dwutlenek krzemu, barwnik: dwutlenek tytanu",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu. Kobiety w ciąży i karmiące piersią, osoby z kamicą nerkową oraz przyjmujące sulfonamidy przed zastosowaniem produktu powinny skonsultować się z lekarzem.",Form="1 kapsułka 2 razy dziennie."},
                new Product() { ProductId = 10, ProductName = "4 flex o smaku czarnej porzeczki x 10 sasz", ProductDescription = "4Flex suplement diety to łatwo przyswajalny hydrolizat kolagenu (Fortigel®) naturalnego pochodzenia w formie saszetek z proszkiem.\n4Flex o smaku czarnej porzeczki. Kolagen nowej generacji + witamina C: łatwo przyswajalny hydrolizat kolagenu Fortigel® naturalnego pochodzenia witamina C pomaga w prawidłowej produkcji kolagenu w celu zapewnienia właściwego funkcjonowania chrząstki i kości.", ProductPrice = 14.32m, CoverFileName = "4flex.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 11, 21),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="hydrolizat kolagenu Fortigel®, regulator kwasowości (kwas cytrynowy), aromat czarnej porzeczki, witamina C (kwas L-askorbinowy), barwnik (koszenila), substancja słodząca (sukraloza).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Zawartość saszetki rozmieszać w 1 szklance niegazowanej wody, mleka lub jogurtu. Mieszać intensywnie do rozpuszczenia proszku. Spożyć bezpośrednio po przygotowaniu. Tworząca się zawiesina jest naturalną cechą produktu. Zaleca się regularne stosowanie przez dłuższy czas (minimum 3 miesiące)."},
                new Product() { ProductId = 11, ProductName = "Acenol 100 mg x 20 tabl", ProductDescription = "W bólach różnego pochodzenia (bóle głowy, zębów, stawowe, miesiączkowe, nerwobóle i inne). Może być jednym z leków w zwalczaniu bólu. Działa przeciwgorączkowo.", ProductPrice = 29.32m, CoverFileName = "aceton.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 11, 21),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="1 tabletka zawiera 100 mg paracetamolu.",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Dzieci od 6 do 12 roku życia: doustnie 1/2 do 1 tabletki trzy lub cztery razy na dobę w odstępach nie krótszych niż 6 godzin\nDorośli i dzieci powyżej 12 roku życia: doustnie jedną do trzech tabletek trzy lub cztery razy na dobę w odstępach nie krótszych niż 4 godziny, maksymalnie trzynaście (13) tabletek na dobę."},
                new Product() { ProductId = 12, ProductName = "Activ krill x 10 kaps (ICN)", ProductDescription = "Suplement diety to łatwo przyswajalny hydrolizat kolagenu (Fortigel®) naturalnego pochodzenia w formie saszetek z proszkiem.\n4Kolagen nowej generacji + witamina C: łatwo przyswajalny hydrolizat kolagenu Fortigel® naturalnego pochodzenia witamina C pomaga w prawidłowej produkcji kolagenu w celu zapewnienia właściwego funkcjonowania chrząstki i kości.", ProductPrice = 14.32m, CoverFileName = "activ.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 11, 21),Prescription = true,MaxQuantity = 100,ManufactureId=3, Components="hydrolizat kolagenu Fortigel®, regulator kwasowości (kwas cytrynowy), aromat czarnej porzeczki, witamina C (kwas L-askorbinowy), barwnik (koszenila), substancja słodząca (sukraloza).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="1-2 kaps dziennie."},

                new Product() { ProductId = 13, ProductName = "Bioliq 25+ krem nawilżający pod oczy 15 ml", ProductDescription = "Krem nawilżający pod oczy - nawilża i regeneruje delikatną skórę wokół oczu. Zmniejsza opuchliznę i cienie. Pielęgnuje i intensywnie nawilża delikatną skórę wokół oczu. Zawarty w kremie wyciąg z orchidei purpurowej (Orchis mascula) działa kojąco i łagodząco. Krem wspomaga regenerację naskórka oraz skutecznie zmniejsza opuchliznę i cienie pod oczami. Dodatkowo chroni skórę przed niekorzystnym wpływem wolnych rodników, opóźniając powstawanie pierwszych zmarszczek.", ProductPrice = 21.14m, CoverFileName = "bio.png", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 11, 21),Prescription = true,MaxQuantity = 100,ManufactureId=2},
                new Product() { ProductId = 14, ProductName = "Gelacet plus x 21 sasz", ProductDescription = "Suplement diety Gelacet Plus to połączenie składników odżywczych wpływających na prawidłową kondycję skóry:Hydrolizat kolagenu jest źródłem kluczowych aminokwasów będących podstawowym budulcem skóry.", ProductPrice = 11.32m, CoverFileName = "gela.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 12, 21),Prescription = true,MaxQuantity = 320,ManufactureId=1,Components="hydrolizat kolagenu (zawierający aminokwasy: glicyna, prolina, hydroksyprolina, kwas glutaminowy, alanina, arginina, kwas asparaginowy, lizyna, seryna, leucyna, walina, fenyloalanina, treonina); regulator kwasowości: kwas cytrynowy; octan DL-alfa-tokoferylu (witamina E); kwas L-askorbinowy (witamina C); naturatny aromat pomarańczowy; maltodekstryna, koncentrat z buraka; barwnik: karoteny; selenian (VI) sodu (selen); tlenek cynku (cynk); substancja słodząca: aspartam; octan retinylu (witamina A); D-biotyna (biotyna).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Należy spożywać 1 saszetkę dziennie, rozpuszczając jej zawartość w ok. 150 ml niegazowanej wody. Zawartość wymieszać i wypić. Zawartość saszetki najlepiej spożyć bezpośrednio po otwarciu"},
                new Product() { ProductId = 15, ProductName = "Benzacne 10% żel 10 g", ProductDescription = "Preparat poprzez działanie przeciwbakteryjne i keratolityczne zmniejsza liczbę zaskórników i powoduje ustępowanie zapalnych wykwitów. Poprawia zaopatrzenie w tlen tkanek. Lek łatwo przechodzi do warstwy rogowej naskórka, tu jest metabolizowany w keratynocytach do kwasu benzoesowego i eliminowany z moczem. Dobra tolerancja pozwala na długotrwałe stosowanie.", ProductPrice = 33.12m, CoverFileName = "benz.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 11, 11),Prescription = true,MaxQuantity = 110,ManufactureId=3,Components="Substancja czynna: nadtlenek benzoilu 0,1 g.",Contraindications="Nadwrażliwość na którykolwiek składnik preparatu. Nie stosować na błony śluzowe.",Form="Dorośli i dzieci powyżej 12 lat: Po umyciu i osuszeniu trądzikowej skóry wciera się delikatnie w miejsca chorobowo zmienione niewielką ilość preparatu unikając okolic oczu, nosa i ust. Zwykle leczenie rozpoczyna się od 5% preparatu 1 raz dziennie przez 2 do 3 tygodni i w razie konieczności kontynuuje 10% żelem."},
                new Product() { ProductId = 16, ProductName = "Elancyl cellu slim krem na cellulit 200 ml", ProductDescription = "Innowacja 2012 - Pierwszy produkt wyszczuplający, ktory usuwa wszystkie rodzaje tłuszczów, nawet tych najbardziej oporonych, dzięki unikalnemu połączeniu CERKOPIA + KOFEINA Udowodniona skuteczność już po 7 DNIACH: Efekt wyszczuplenia już po 7 dniach, widoczne wygładzenie 'skórki pomarańczowej' już po 14 dniach (na podstawie badań biometrycznych: pomiar w centymentrach obwodu ud na grupie 44 kobiet po 7 dniach stosowania Elancyl Cellu Slim, test konsumencki na grupie 89 kobiet po 14 dniach stosowania Elancyl Cellu Slim).", ProductPrice = 89.12m, CoverFileName = "elan.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 11, 10),Prescription = true,MaxQuantity = 90,ManufactureId=3,Components="Cekropia - wyciąg z tropikalnej rośliny z rodziny morwowatych, działanie rozbijające i usuwające wszystkie rodzaje tłuszczów Kofeina - stymuluje przemianę materii, dodatkowo usuwając złogi tłuszczów. Działanie drenujące tkanek przyczynia się do wyszczuplania Bluszcz: usuwanie toksyn i nadmiaru wody.",Form="Jeden raz dziennie nałóż ELANCYL Cellu Slim na uda i pośladki wykonując okrężne, masujące ruchy zgodnie z ruchem wskazówek zegara, najlepiej rano. Krem natychmiast się wchłania i nie pozostawia plam na ubraniach. Opakownie 200ml wystarcza na 1 miesiąc kuracji.Skuteczność produktu zależy od przestrzegania zaleceń dotyczących sposobu i regularności stosowania oraz zdrowego trybu życia. Unikać kontaktu z oczami. Nie stosować na podrażnioną skórę.."},
                new Product() { ProductId = 17, ProductName = "Mosquiterum spray 100 ml", ProductDescription = "Spray na skórę.", ProductPrice = 56.53m, CoverFileName = "mos.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 5 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 2000,ManufactureId=2,Components="Zawiera składniki pochodzenia naturalnego, które odżywiają i wspierają funkcje ochronne skóry (olej z bawełny, olej z aloesu), oraz naturalne olejki eteryczne (olejek citronella, olejek z trawy cytrynowej i olejek z kocimiętki), które tworzą barierę zapachową przed owadami (w szczególności komarami, muchami i meszkami).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Kosmetyk należy rozpylić na powierzchni skóry. W razie potrzeby aplikację powtarzać co 2-3 godziny."},
                new Product() { ProductId = 18, ProductName = "Nutridrink juice style o smaku jabłkowym 4 x 200 ml", ProductDescription = "Dieta beztłuszczowa, hiperkaloryczna (1,5 kcal/ml). Oparta na białku serwatkowym Źródłem węglowodanów są maltodekstryny i sacharoza. Niska zawartość sodu i fosforanów.", ProductPrice = 32.12m, CoverFileName = "nut.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 5 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 4320,ManufactureId=1,Components="Węglowodany, w tym:- cukry proste i dwucukry Białko ",Contraindications="Stosować pod nadzorem lekarza. Nie stosować u dzieci poniżej 3 lat. Podając dzieciom w wieku od 3 do 6 lat należy zachować szczególne środki ostrożności. Nie stosować w przypadku alergii na białka mleka krowiego, galaktozemii i fruktozemii. Nie może być jedynym źródłem pożywienia.",Form="Tylko jako uzupełnienie diety: 1 - 3 opakowania dziennie (100 - 900 kcal) lub zgodnie ze wskazaniami lekarza. Produkt gotowy do spożycia, przeznaczony do picia. Najlepiej podawać schłodzony. Dobrze wstrząsnąć przed użyciem. Produkt zaleca się pić powoli (1 opakowanie od 10 min do 1 godz.), między posiłkami."},
                
                new Product() { ProductId = 19, ProductName = "Ubichinol koenzym q10 x 60 kaps", ProductDescription = "50 mg Ubichinolu = 400 mg Koenzymu Q10 Koenzym Q10 często nazywany jest witaminą młodości i długowieczności, a za odkrycie jego funkcji dwukrotnie przyznano nagrodę Nobla.Koenzym Q10 to produkt najwyższej jakości pochodzący z procesu ekstrakcji fermentowanych drożdży, nie posiada formy cis i jest identyczny w swojej budowie do wytwarzanego przez organizm ludzki.", ProductPrice = 14.34m, CoverFileName = "ubi.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 876,ManufactureId=5,Components="Ubiquinol® (KanekaQ10™)aktywna forma koenzymu Q10 Substancje pomocnicze: stearynian magnezu, celuloza mikrokrystaliczna",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Stosować 2 kapsułki dziennie.."},
                new Product() { ProductId = 20, ProductName = "Hesperydynin x 60 kaps", ProductDescription = "Hesperydynin uzupełnia dietę we flawonoidy i inne związki, które pozytywnie wspierają funkcjonowanie organizmu człowieka.", ProductPrice = 96.75m, CoverFileName = "hes.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1 ,DateEnd = new DateTime(2017, 01, 23),Prescription = true,MaxQuantity = 765,ManufactureId=4,Components="hesperydyna 95%, daidzeina (wyciąg z soi) 98%, indolo – 3 – karbinol (wyciąg z brokułów i brukselki) 100%, kwercetyna (wyciąg z cebuli) 95%, resweratrol (wyciąg z pestek winogron) 80 %, silimaryna (wyciąg z ostropestu plamistego) 80 %, kurkumina (wyciąg z kurkumy) 95%, celuloza mikrokrystaliczna, stearynian magnezu",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Stosować 1 kapsułkę dziennie."},
                //new Product() { ProductId = 21, ProductName = "", ProductDescription = ".", ProductPrice = 32.12m, CoverFileName = "nut.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 4320,ManufactureId=1,Components="",Contraindications=".",Form="."},
               

                new Product() { ProductId = 21, ProductName = "Mosquiterum spray 200 ml", ProductDescription = "Spray na skórę.", ProductPrice = 100.11m, CoverFileName = "mos.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 2120,ManufactureId=2,Components="Zawiera składniki pochodzenia naturalnego, które odżywiają i wspierają funkcje ochronne skóry (olej z bawełny, olej z aloesu), oraz naturalne olejki eteryczne (olejek citronella, olejek z trawy cytrynowej i olejek z kocimiętki), które tworzą barierę zapachową przed owadami (w szczególności komarami, muchami i meszkami).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Kosmetyk należy rozpylić na powierzchni skóry. W razie potrzeby aplikację powtarzać co 2-3 godziny."},
                new Product() { ProductId = 22, ProductName = "Mosquiterum spray 50 ml", ProductDescription = "Spray na skórę.", ProductPrice = 10.00m, CoverFileName = "mos.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 2 ,DateEnd = new DateTime(2017, 01, 31),Prescription = true,MaxQuantity = 800,ManufactureId=2,Components="Zawiera składniki pochodzenia naturalnego, które odżywiają i wspierają funkcje ochronne skóry (olej z bawełny, olej z aloesu), oraz naturalne olejki eteryczne (olejek citronella, olejek z trawy cytrynowej i olejek z kocimiętki), które tworzą barierę zapachową przed owadami (w szczególności komarami, muchami i meszkami).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Kosmetyk należy rozpylić na powierzchni skóry. W razie potrzeby aplikację powtarzać co 2-3 godziny."},
                new Product() { ProductId = 23, ProductName = "Reliver x 60 kaps", ProductDescription = "Suplement diety zalecany dla osób, których wątroba narażona jest na działanie  alkoholu, leków i dieta ciężkostrawna.Wspomaga prawidłowe funkcjonowanie wątroby.", ProductPrice = 33.11m, CoverFileName = "1.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1 ,DateEnd = new DateTime(2016, 02, 23),Prescription = true,MaxQuantity = 211,ManufactureId=1, Components="lecytyna rzepakowa, składnik otoczki: żelatyna wołowa, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych, wodny ekstrakt z liści karczocha (Cynara scolymus L.) DER 6:1, standaryzowany na 5% cynaryny, substancja wypełniająca: celuloza, L-asparaginian L-ornityny, substancja przeciwzbrylająca: dwutlenek krzemu, barwnik: dwutlenek tytanu, chlorowodorek pirydoksyny (witamina B6), ryboflawina (witamina B2)",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu.",Form="Zalecana porcja do spożycia w ciągu dnia: 1 kapsułka 1-2 razy dziennie w trakcie lub po posiłku."},
                new Product() { ProductId = 24, ProductName = "Reliver x 100 kaps", ProductDescription = "Suplement diety zalecany dla osób, których wątroba narażona jest na działanie  alkoholu, leków i dieta ciężkostrawna.Wspomaga prawidłowe funkcjonowanie wątroby.", ProductPrice = 42.01m, CoverFileName = "1.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2016, 02, 11),Prescription = true,MaxQuantity = 423,ManufactureId=1, Components="lecytyna rzepakowa, składnik otoczki: żelatyna wołowa, substancja przeciwzbrylająca: sole magnezowe kwasów tłuszczowych, wodny ekstrakt z liści karczocha (Cynara scolymus L.) DER 6:1, standaryzowany na 5% cynaryny, substancja wypełniająca: celuloza, L-asparaginian L-ornityny, substancja przeciwzbrylająca: dwutlenek krzemu, barwnik: dwutlenek tytanu, chlorowodorek pirydoksyny (witamina B6), ryboflawina (witamina B2)",Contraindications="Nie należy stosować w przypadku uczulenia (nadwrażliwości) na którykolwiek ze składników produktu.",Form="Zalecana porcja do spożycia w ciągu dnia: 1 kapsułka 1-2 razy dziennie w trakcie lub po posiłku."},

                new Product() { ProductId = 25, ProductName = "Acenol 100 mg x 50 tabl", ProductDescription = "W bólach różnego pochodzenia (bóle głowy, zębów, stawowe, miesiączkowe, nerwobóle i inne). Może być jednym z leków w zwalczaniu bólu. Działa przeciwgorączkowo.", ProductPrice = 32.32m, CoverFileName = "ace.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2019, 11, 21),Prescription = true,MaxQuantity = 310,ManufactureId=3, Components="1 tabletka zawiera 100 mg paracetamolu.",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Dzieci od 6 do 12 roku życia: doustnie 1/2 do 1 tabletki trzy lub cztery razy na dobę w odstępach nie krótszych niż 6 godzin\nDorośli i dzieci powyżej 12 roku życia: doustnie jedną do trzech tabletek trzy lub cztery razy na dobę w odstępach nie krótszych niż 4 godziny, maksymalnie trzynaście (13) tabletek na dobę."},
                new Product() { ProductId = 26, ProductName = "Acenol 100 mg x 100 tabl", ProductDescription = "W bólach różnego pochodzenia (bóle głowy, zębów, stawowe, miesiączkowe, nerwobóle i inne). Może być jednym z leków w zwalczaniu bólu. Działa przeciwgorączkowo.", ProductPrice = 46.04m, CoverFileName = "aceton.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1 ,DateEnd = new DateTime(2016, 04, 03),Prescription = true,MaxQuantity = 900,ManufactureId=3, Components="1 tabletka zawiera 100 mg paracetamolu.",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Dzieci od 6 do 12 roku życia: doustnie 1/2 do 1 tabletki trzy lub cztery razy na dobę w odstępach nie krótszych niż 6 godzin\nDorośli i dzieci powyżej 12 roku życia: doustnie jedną do trzech tabletek trzy lub cztery razy na dobę w odstępach nie krótszych niż 4 godziny, maksymalnie trzynaście (13) tabletek na dobę."},
                new Product() { ProductId = 27, ProductName = "Acenol 100 mg x 150 tabl", ProductDescription = "W bólach różnego pochodzenia (bóle głowy, zębów, stawowe, miesiączkowe, nerwobóle i inne). Może być jednym z leków w zwalczaniu bólu. Działa przeciwgorączkowo.", ProductPrice = 78.21m, CoverFileName = "ace.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 08, 09),Prescription = true,MaxQuantity = 932,ManufactureId=3, Components="1 tabletka zawiera 100 mg paracetamolu.",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Dzieci od 6 do 12 roku życia: doustnie 1/2 do 1 tabletki trzy lub cztery razy na dobę w odstępach nie krótszych niż 6 godzin\nDorośli i dzieci powyżej 12 roku życia: doustnie jedną do trzech tabletek trzy lub cztery razy na dobę w odstępach nie krótszych niż 4 godziny, maksymalnie trzynaście (13) tabletek na dobę."},


                new Product() { ProductId = 28, ProductName = "Hesperydynin x 20 kaps", ProductDescription = "Hesperydynin uzupełnia dietę we flawonoidy i inne związki, które pozytywnie wspierają funkcjonowanie organizmu człowieka.", ProductPrice = 48m, CoverFileName = "hysp.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2017, 01, 23),Prescription = true,MaxQuantity = 765,ManufactureId=4,Components="hesperydyna 95%, daidzeina (wyciąg z soi) 98%, indolo – 3 – karbinol (wyciąg z brokułów i brukselki) 100%, kwercetyna (wyciąg z cebuli) 95%, resweratrol (wyciąg z pestek winogron) 80 %, silimaryna (wyciąg z ostropestu plamistego) 80 %, kurkumina (wyciąg z kurkumy) 95%, celuloza mikrokrystaliczna, stearynian magnezu",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Stosować 1 kapsułkę dziennie."},
                new Product() { ProductId = 29, ProductName = "Hesperydynin x 90 kaps", ProductDescription = "Hesperydynin uzupełnia dietę we flawonoidy i inne związki, które pozytywnie wspierają funkcjonowanie organizmu człowieka.", ProductPrice = 150.75m, CoverFileName = "hes.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2017, 01, 23),Prescription = true,MaxQuantity = 765,ManufactureId=4,Components="hesperydyna 95%, daidzeina (wyciąg z soi) 98%, indolo – 3 – karbinol (wyciąg z brokułów i brukselki) 100%, kwercetyna (wyciąg z cebuli) 95%, resweratrol (wyciąg z pestek winogron) 80 %, silimaryna (wyciąg z ostropestu plamistego) 80 %, kurkumina (wyciąg z kurkumy) 95%, celuloza mikrokrystaliczna, stearynian magnezu",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Stosować 1 kapsułkę dziennie."},
                new Product() { ProductId = 10, ProductName = "Hesperydynin x 120 kaps", ProductDescription = "Hesperydynin uzupełnia dietę we flawonoidy i inne związki, które pozytywnie wspierają funkcjonowanie organizmu człowieka.", ProductPrice = 200.11m, CoverFileName = "hysp.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4 ,DateEnd = new DateTime(2017, 01, 23),Prescription = true,MaxQuantity = 765,ManufactureId=4,Components="hesperydyna 95%, daidzeina (wyciąg z soi) 98%, indolo – 3 – karbinol (wyciąg z brokułów i brukselki) 100%, kwercetyna (wyciąg z cebuli) 95%, resweratrol (wyciąg z pestek winogron) 80 %, silimaryna (wyciąg z ostropestu plamistego) 80 %, kurkumina (wyciąg z kurkumy) 95%, celuloza mikrokrystaliczna, stearynian magnezu",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu.",Form="Stosować 1 kapsułkę dziennie."},

                new Product() { ProductId = 31, ProductName = "4 flex o smaku czarnej porzeczki x 60 sasz", ProductDescription = "4Flex suplement diety to łatwo przyswajalny hydrolizat kolagenu (Fortigel®) naturalnego pochodzenia w formie saszetek z proszkiem.\n4Flex o smaku czarnej porzeczki. Kolagen nowej generacji + witamina C: łatwo przyswajalny hydrolizat kolagenu Fortigel® naturalnego pochodzenia witamina C pomaga w prawidłowej produkcji kolagenu w celu zapewnienia właściwego funkcjonowania chrząstki i kości.", ProductPrice = 21.90m, CoverFileName = "4fl.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 11, 11),Prescription = true,MaxQuantity = 5000,ManufactureId=3, Components="hydrolizat kolagenu Fortigel®, regulator kwasowości (kwas cytrynowy), aromat czarnej porzeczki, witamina C (kwas L-askorbinowy), barwnik (koszenila), substancja słodząca (sukraloza).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Zawartość saszetki rozmieszać w 1 szklance niegazowanej wody, mleka lub jogurtu. Mieszać intensywnie do rozpuszczenia proszku. Spożyć bezpośrednio po przygotowaniu. Tworząca się zawiesina jest naturalną cechą produktu. Zaleca się regularne stosowanie przez dłuższy czas (minimum 3 miesiące)."},
                new Product() { ProductId = 32, ProductName = "4 flex o smaku czarnej porzeczki x 90 sasz", ProductDescription = "4Flex suplement diety to łatwo przyswajalny hydrolizat kolagenu (Fortigel®) naturalnego pochodzenia w formie saszetek z proszkiem.\n4Flex o smaku czarnej porzeczki. Kolagen nowej generacji + witamina C: łatwo przyswajalny hydrolizat kolagenu Fortigel® naturalnego pochodzenia witamina C pomaga w prawidłowej produkcji kolagenu w celu zapewnienia właściwego funkcjonowania chrząstki i kości.", ProductPrice = 10.10m, CoverFileName = "4flex.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 3 ,DateEnd = new DateTime(2016, 03, 21),Prescription = true,MaxQuantity = 2001,ManufactureId=3, Components="hydrolizat kolagenu Fortigel®, regulator kwasowości (kwas cytrynowy), aromat czarnej porzeczki, witamina C (kwas L-askorbinowy), barwnik (koszenila), substancja słodząca (sukraloza).",Contraindications="Nadwrażliwość na którykolwiek ze składników preparatu. Preparat przeznaczony wyłącznie dla osób dorosłych. Kobiety w ciąży i matki karmiące piersią przed zastosowaniem powinny skonsultować się z lekarzem.",Form="Zawartość saszetki rozmieszać w 1 szklance niegazowanej wody, mleka lub jogurtu. Mieszać intensywnie do rozpuszczenia proszku. Spożyć bezpośrednio po przygotowaniu. Tworząca się zawiesina jest naturalną cechą produktu. Zaleca się regularne stosowanie przez dłuższy czas (minimum 3 miesiące)."},

                new Product() { ProductId = 33, ProductName = "Kardiostabil x 60 tabl", ProductDescription = "Przeznaczony dla osób dorosłych. Magnez przyczynia się do prawidłowego funkcjonowania mięśni, w tym mięśnia sercowego. Magnez może przyczynić się do zmniejszenia zmęczenia. Głóg dwuszyjkowy wspiera pracę serca, wpływa na poprawę krążenia obwodowego krwi.", ProductPrice = 10.10m, CoverFileName = "kard.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1 ,DateEnd = new DateTime(2016, 03, 21),Prescription = true,MaxQuantity = 2001,ManufactureId=5, Components="glukonian magnezu , wyciąg z owoców głogu dwuszyjkowego , skrobia ziemniaczana (substancja wypełniająca), metyloceluloza (nośnik), stearynian magnezu (substancja przeciwzbrylająca), dwutlenek krzemu (substancja przeciwzbrylająca).",Form="Zaleca się przyjmowanie 2 tabletek 2 razy dziennie po posiłku, popijając wodą."},
                new Product() { ProductId = 34, ProductName = "Paracetamol", ProductDescription = "Przeznaczony dla osób dorosłych. Magnez przyczynia się do prawidłowego funkcjonowania mięśni, w tym mięśnia sercowego. Magnez może przyczynić się do zmniejszenia zmęczenia. Głóg dwuszyjkowy wspiera pracę serca, wpływa na poprawę krążenia obwodowego krwi.", ProductPrice = 10.10m, CoverFileName = "para.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 4,DateEnd = new DateTime(2016, 03, 21),Prescription = true,MaxQuantity = 2001,ManufactureId=4, Components="glukonian magnezu , wyciąg z owoców głogu dwuszyjkowego , skrobia ziemniaczana (substancja wypełniająca), metyloceluloza (nośnik), stearynian magnezu (substancja przeciwzbrylająca), dwutlenek krzemu (substancja przeciwzbrylająca).",Form="Zaleca się przyjmowanie 2 tabletek 2 razy dziennie po posiłku, popijając wodą."},
                new Product() { ProductId = 35, ProductName = "Flu Control Max", ProductDescription = "FluControl MAX to maksymalne dawki substancji czynnych.* Dlatego jedna tabletka wystarczy, aby poczuć ulgę od uciążliwych symptomów choroby.", ProductPrice = 45.10m, CoverFileName = "flu.png", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 1,DateEnd = new DateTime(2016, 03, 21),Prescription = true,MaxQuantity = 2001,ManufactureId=4, Components="1 tabletka (1 dawka) FluControl MAX zawiera: 650mg paracetamolu 10mg chlorowodorku fenylefryny 4mg maleinianu chlorfenaminy).",Form="Zaleca się przyjmowanie 2 tabletek 2 razy dziennie po posiłku, popijając wodą."},

                new Product() { ProductId = 36, ProductName = "Apap Extra 20 kaps", ProductDescription = "Apap Extra to maksymalne dawki substancji czynnych.* Dlatego jedna tabletka wystarczy, aby poczuć ulgę od uciążliwych symptomów choroby.", ProductPrice = 21.10m, CoverFileName = "apap.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 5,DateEnd = new DateTime(2017, 05, 11),Prescription = true,MaxQuantity = 2001,ManufactureId=4, Components="1 tabletka (1 dawka) FluControl MAX zawiera: 650mg paracetamolu 10mg chlorowodorku fenylefryny 4mg maleinianu chlorfenaminy).",Form="Zaleca się przyjmowanie 2 tabletek 2 razy dziennie po posiłku, popijając wodą."},
                new Product() { ProductId = 37, ProductName = "Ibuprom max", ProductDescription = "Ibuprom max to maksymalne dawki substancji czynnych.* Dlatego jedna tabletka wystarczy, aby poczuć ulgę od uciążliwych symptomów choroby.", ProductPrice = 32.22m, CoverFileName = "ibuprom.jpg", IsBestseller = true, DateAdded = new DateTime(2015, 02, 1), CategoryId = 5,DateEnd = new DateTime(2016, 06, 21),Prescription = true,MaxQuantity = 2901,ManufactureId=4, Components="1 tabletka (1 dawka) FluControl MAX zawiera: 650mg paracetamolu 10mg chlorowodorku fenylefryny 4mg maleinianu chlorfenaminy).",Form="Zaleca się przyjmowanie 2 tabletek 2 razy dziennie po posiłku, popijając wodą."},


            };
            products.ForEach(a =>
            {
                TimeSpan ts = a.DateEnd - DateTime.Now;
                int between = ts.Days;
                if (between <= 60)
                    a.ProductPrice = 0.7M * a.ProductPrice;
                else if (between < 90 && between > 60)
                    a.ProductPrice = 0.8M * a.ProductPrice;
                else if (between < 120 && between >= 90)
                    a.ProductPrice = 0.9M * a.ProductPrice;


            });
            products.ForEach(a => context.Products.AddOrUpdate(a));
            context.SaveChanges();

            var bonusCodes = new List<BonusCode>
            {
                new BonusCode(){BonusCodeId=1,Code="32489sdawd"},
                new BonusCode(){BonusCodeId=2,Code="3w489s32wd"},
                new BonusCode(){BonusCodeId=3,Code="s242v$#dw0"},
                new BonusCode(){BonusCodeId=4,Code="s242vsddw3"},
                new BonusCode(){BonusCodeId=5,Code="duej3dec#3"},
                new BonusCode(){BonusCodeId=6,Code="dfsjdfsjh6"},
                new BonusCode(){BonusCodeId=7,Code="c242dfssw0"},
                new BonusCode(){BonusCodeId=8,Code="s2e2vsedw3"},
                new BonusCode(){BonusCodeId=9,Code="1242vsd4w5"},

            };

            bonusCodes.ForEach(c => context.BonusCodes.AddOrUpdate(c));
            context.SaveChanges();
        }
        public static void InitializeIdentityForEF(StoreContext db)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            //var userManager = HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
            //var roleManager = HttpContext.Current.GetOwinContext().Get<ApplicationRoleManager>();
            const string name = "admin@hurtownia.pl";
            const string password = "P@ssw0rd";
            const string roleName = "Admin";
            const string firstName = "Jan";
            const string lastName = "Nowak";

            const string phoneNumber = "233233";
            const string address = "Al. Kowalskiego, Siedlce";
            const string codeAndCity = "08-100 Siedlce";
            const string factory = "Firma Admina";
            const string nip = "824-451-57-12";
            UserData userData = new UserData() { FirstName = firstName, LastName = lastName, Factory = factory, Nip = nip, Address = address, PhoneNumber = phoneNumber, CodeAndCity = codeAndCity, Email = name };

            var user = userManager.FindByName(name);
            if (user == null)
            {
                //tworzy admina
                user = new ApplicationUser { UserName = name, Email = name, UserData = userData };
                //utw w bazie usera
                var result = userManager.Create(user, password);
                result = userManager.SetLockoutEnabled(user.Id, false);
            }

            //Create Role Admin if it does not exist
            var role = roleManager.FindByName(roleName);
            if (role == null)
            {
                role = new IdentityRole(roleName);
                //dodajemy role
                var roleresult = roleManager.Create(role);
            }

            //var user = userManager.FindByName(name);
            //if (user == null)
            //{
            //    user = new ApplicationUser { UserName = name, Email = name };
            //    var result = userManager.Create(user, password);
            //    result = userManager.SetLockoutEnabled(user.Id, false);
            //}

            // Add user admin to Role Admin if not already added
            var rolesForUser = userManager.GetRoles(user.Id);
            if (!rolesForUser.Contains(role.Name))
            {
                var result = userManager.AddToRole(user.Id, role.Name);
            }
        }
    }
}