// <auto-generated />
namespace Hurtownia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lista_kategorii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lista_kategorii));
        
        string IMigrationMetadata.Id
        {
            get { return "201504021619563_lista_kategorii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
